apiVersion: v1
kind: Service
metadata:
  name: cnss-front
  namespace: cnss
spec:
  type: NodePort
  selector:
    app: cnss-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
