apiVersion: v1
data:
  .dockerconfigjson: eWVybWFuaW1vaGFtZWQ6ZGNrcl9wYXRfcGpfY3pWdnVvNl93NWtMMWh2M2RIb1VrRVlV
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: cnss
  name: dockerhub-pull-secret
  namespace: cnss
type: kubernetes.io/dockerconfigjson
