apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnss-uploadedfiles-pvc
  namespace: cnss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: cnss-uploadedfiles-pv
