apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnss_backend-uploadedfiles-pv
  namespace: cnss
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/cnss-uploadedfiles"